type ErrorCode = {
  UNKNOWN_ERROR_CODE: string;
  ITEM_CREATION_FAILED_CODE: string;
  EXTERNAL_LOOKUP_FAILED_CODE: string;
  INVALID_PARAMETER_CODE: string;
};

export const ERROR_CODE: ErrorCode = {
  UNKNOWN_ERROR_CODE: "UNKNOWN_ERROR",
  ITEM_CREATION_FAILED_CODE: "ITEM_CREATION_FAILED",
  EXTERNAL_LOOKUP_FAILED_CODE: "EXTERNAL_LOOKUP_FAILED",
  INVALID_PARAMETER_CODE: "INVALID_PARAMETER"
};
